application:
  subdomain: wechat-selkies
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://wechat-selkies:3000/
services:
  wechat-selkies:
    # nickrunning/wechat-selkies:0.0.5
    # upstream: docker.io/nickrunning/wechat-selkies:0.0.17
    image: docker.1ms.run/nickrunning/wechat-selkies:0.0.17
    user: root
    binds:
      - /lzcapp/var/config:/config
    environment:
      - PUID=1000 # user ID
      - PGID=100 # group ID
      - TZ={{.U.timezone}} # timezone
      - LC_ALL=zh_CN.UTF-8 # locale
      - AUTO_START_WECHAT={{.U.auto_start_wechat}} # default is true
      - AUTO_START_QQ={{.U.auto_start_qq}} # default is false
